### ISSUE TITLE
How to do SR on the whole picture

### ISSUE THREAD

**Issue by 619862306** [riccardodelutio/PixTransform#1]
Thank you for your work. As shown in your paper，the results are all patches operations. So i padding zero around the pictures to n*n resolution, then i run the program. However, the results are not good. 
![Art](https://user-images.githubusercontent.com/49178624/70680934-9e239d00-1cd4-11ea-9aa5-5f07326325f1.png)
![Cones](https://user-images.githubusercontent.com/49178624/70680942-a380e780-1cd4-11ea-83df-2e7e0c2c75b4.png)
The ratio of downsampling is 8.  Is it due to padding zero?

**Comment by riccardodelutio** [comment]
Hi, it looks like the issue might be more to do with the regularisation. The regularisation values might need to be modified when changing the size of the input image. 

Another option to run the method on the entire images would be to run it patchwise. For that I would recommend using patches of the original size (256x256 output size) that have an overlap and for every pixel location to select the median of all the outputs that overlap at that location. 

I hope this helps!

**Comment by 619862306** [comment]
Thank you for your suggestion.
