### ISSUE TITLE
Some question about the paper

### ISSUE THREAD

**Issue by jucic** [riccardodelutio/PixTransform#3]
As mentioned in the issue openned by @codyshen0000, the proposed network uses the source image(low reso depth image) only at the training stage(to construct the loss func), and it directly transform the guide image(color image/gray image) to the target image(depth) without the source image at the inference stage, so I think the network should be a Monocular-Depth-Estimation network rather than a Super-Resolution network.

**Comment by riccardodelutio** [comment]
Thanks for your interest in our work! Just to clarify, this work is about Guided Super-Resolution this means the goal is to increase the resolution of a **low-res source image** with the help of a **high-res guide image**. 

In the specific case of depth map guided super-resolution (our method is not limited to this application) the **source is a low-res depth map** of a scene, **the high-res guide is the corresponding high-res RGB** of the same scene and our desired **output is the high-res depth map**. That's a very common setup, for instance in smartphones that are equipped with a standard camera and a TOF camera (or laser scanner), same goes with robots or other autonomous systems.

The difference with Monocular Depth Estimation is that we are provided with a low-res depth map to start with, which we use to supervise our method. The other key difference is that our method is completely unsupervised: we only need a single pair of images to provide an output, the source and the guide, we don't use any high-res output images as labels to supervise. 

I hope this helps! In case it's still a bit confusing by looking at the code only, I would recommend reading our paper.
