### ISSUE TITLE
The size does not match in  pix_transform?

### ISSUE THREAD

**Issue by JuZiSYJ** [riccardodelutio/PixTransform#4]
Hi!
in your infer code
`predicted_target_img = PixTransform(guide_img=guide_img,source_img=source_img,params=params,target_img=target_img)`

source_img is  N\*N < M\*M

while in your code  Pixtransform/pix_transform.py, line91
`    for i in range(0, M):
        for j in range(0, M):
            guide_patches[j + i * M, :, :, :] = guide_img[:, i * D:(i + 1) * D, j * D:(j + 1) * D]
            **source_pixels[j + i * M] = source_img[i:(i + 1), j:(j + 1)]**`

I am confused because the  **source_img** is of **N*N,** while the index can be larger than N!

Besides, the guide_path can be a writer with  torch.unfold(), which is fast than  for..for..

**Comment by riccardodelutio** [comment]
Hi, thanks for your question!

I think you are confusing M and N, in fact: M is the size of the low-res source image and N the size of the high-res guide. 
So M < N. 

You can check in Pixtransform/pix_transform.py, line 48 
```
    lr_height, lr_width = source_img.shape
```
and line 55 
```
    M = lr_height
```

And regarding the performance yes the code can be drastically optimised, this wasn't the focus of our work,  we mainly aimed at keeping it as readable as possible.
